wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.7
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1742340106
    t:
      1:
      - 1
      - 5
      - 30
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 30
      - 49
      - 51
      - 53
      - 55
      3:
      - 13
      - 23
      - 61
      4: 3.12.7
      5: 0.17.8
      8:
      - 5
      13: linux-x86_64
